### ISSUE TITLE
parser error (godot 3.1)

### ISSUE THREAD

**Issue by LinuxUserGD** [Faless/godot-websocket-demo#2]
```Swift
peer.put_packet(bytes2var("First UTF-8 message: Það fer nú að verða verra ferðaveðrið"))
```

![bug](https://user-images.githubusercontent.com/34406967/56741301-ece6eb80-6772-11e9-909f-6256d16d32cf.png)

**Comment by Faless** [comment]
Closing as fixed in d0c79d783f581105b2e56a0d073ae615c31a2bb6
